WebsiteBanSach/WebsiteBanSach/Controllers/ChuDeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using webbansach.Model;
using WebsiteBanSach.Models;

namespace webbansach.Controllers
{
    public class ChuDeController : Controller
    {
        //
        // GET: /ChuDe/
        QuanLyBanSachEntities db = new QuanLyBanSachEntities();
        public ActionResult ChuDePartial()
        {
            return PartialView(db.ChuDes.Take(5).ToList());
        }
        //sach theo chu de//
        public ViewResult SachTheoChuDe ( int MaChuDe = 0)
        {
            //kiem tra chu de ton tai hay khong//
            ChuDe cd = db.ChuDes.SingleOrDefault(n => n.MaChuDe == MaChuDe);
            if(cd == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            //truy xuat danh sach cac quyen sach theo chu de//

            List<Sach> lstSach = db.Saches.Where(n=>n.MaChuDe==MaChuDe).OrderBy(n=>n.GiaBan).ToList(); 
            if(lstSach.Count==0)
            {
                ViewBag.Sach="Không có sách nào thuộc chủ đề này: ";

            }
            return View(lstSach);
        }
      
    }
}

WebsiteBanSach/WebsiteBanSach/Controllers/LienHeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebsiteBanSach.Controllers
{
    public class LienHeController : Controller
    {
        //
        // GET: /LienHe/

        public ActionResult Index()
        {
            return View();
        }

    }
}

WebsiteBanSach/WebsiteBanSach/Controllers/SachController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using webbansach.Model;
using WebsiteBanSach.Models;

namespace webbansach.Controllers
{
    public class SachController : Controller
    {
        //
        QuanLyBanSachEntities db = new QuanLyBanSachEntities();
        // GET: /Sach/
        public PartialViewResult SachMoiPartial()
        {
            var lstSachMoi = db.Saches.Take(3).ToList();
            return PartialView(lstSachMoi);
        }
        public ViewResult XemChiTiet(int MaSach = 0)
        {
            Sach sach = db.Saches.SingleOrDefault(n => n.MaSach == MaSach);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            ViewBag.TenChuDe = db.ChuDes.Single(n => n.MaChuDe==sach.MaChuDe).TenChuDe;
            ViewBag.NhaXuatBan = db.NhaXuatBans.Single(n => n.MaNXB == sach.MaNXB).TenNXB;

            return View(sach);
        }
    }
}

WebsiteBanSach/WebsiteBanSach/Controllers/TimKiemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteBanSach.Models;
using PagedList.Mvc;
using PagedList;

namespace WebsiteBanSach.Controllers
{
    public class TimKiemController : Controller
    {
        //
        // GET: /TimKiem/
        QuanLyBanSachEntities db = new QuanLyBanSachEntities();
        [HttpPost]
        public ActionResult KetQuaTimKiem(FormCollection f,int? page)
        {
            string sTuKhoa = f["txtTimKiem"].ToString();
            ViewBag.TuKhoa = sTuKhoa;
            List<Sach> lstKQTK = db.Saches.Where(n => n.TenSach.Contains(sTuKhoa)).ToList();
            // phân trang
            int pageNumber = (page ?? 1);
            int pageSize = 9; 
            
            if(lstKQTK.Count==0)
            {
                ViewBag.ThongBao = "Không tìm thấy sản phẩm";
                return View(db.Saches.OrderBy(n => n.TenSach).ToPagedList(pageNumber, pageSize));
            }
            ViewBag.ThongBao = "Đã tìm thấy" +" "+ lstKQTK.Count+" "+ "kết quả";
            return View(lstKQTK.OrderBy(n => n.TenSach).ToPagedList(pageNumber, pageSize));
        }
        [HttpGet]
        public ActionResult KetQuaTimKiem(string sTuKhoa, int? page)
        {
            ViewBag.TuKhoa = sTuKhoa;
            List<Sach> lstKQTK = db.Saches.Where(n => n.TenSach.Contains(sTuKhoa)).ToList();
            // phân trang
            int pageNumber = (page ?? 1);
            int pageSize = 9;

            if (lstKQTK.Count == 0)
            {
                ViewBag.ThongBao = "Không tìm thấy sản phẩm";
                return View(db.Saches.OrderBy(n => n.TenSach).ToPagedList(pageNumber, pageSize));
            }
            ViewBag.ThongBao = "Đã tìm thấy" + lstKQTK.Count + "kết quả";
            return View(lstKQTK.OrderBy(n => n.TenSach).ToPagedList(pageNumber, pageSize));
        }
    }
}

WebsiteBanSach/WebsiteBanSach/Views/Layout/AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @*chèn font*@

    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
    @*chèn css*@

    <link href="~/TemplateAdmin/assets/css/animate.min.css" rel="stylesheet" />
    <link href="~/TemplateAdmin/assets/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/TemplateAdmin/assets/css/demo.css" rel="stylesheet" />
    <link href="~/TemplateAdmin/assets/css/light-bootstrap-dashboard.css" rel="stylesheet" />
    <link href="~/TemplateAdmin/assets/css/pe-icon-7-stroke.css" rel="stylesheet" />
    <link href="~/TemplateAdmin/documentation/css/documentation.css" rel="stylesheet" />
    @*chèn tinymce *@
    <script src="~/tinymce_6.2.0/tinymce/js/tinymce/tinymce.min.js"></script>

    <script>tinymce.init({ selector: 'textarea' });</script>
 
</head>
<body>
   
    <div>
        <div class="wrapper">
            <div class="sidebar" data-image="../assets/img/sidebar-5.jpg">
                <!--
                Tip 1: You can change the color of the sidebar using: data-color="purple | blue | green | orange | red"

                Tip 2: you can also add an image using data-image tag
            -->

                <div class="sidebar-wrapper">
                    <div class="logo">
                        <a href="http://www.creative-tim.com" class="simple-text">
                            Creative Tim
                        </a>
                    </div>


                    
                    <ul class="nav">
                        @if (Session["TaiKhoan"] != null)
                        {

                            
                        <li class="nav-item active">
                            @Html.ActionLink("Quản lý sản phẩm","Index", "QuanLySanPham")
                               
                        </li>
                        <li>
                            @Html.ActionLink("Quản lý user","Index","QuanLyUser")
                               
                        </li>
                        <li>
                           @Html.ActionLink("Quản lý đơn hàng ","Index","QuanLyDonHang")
                                
                        </li>
                        <li>
                            <a class="nav-link" href="./typography.html">
                                <i class="nc-icon nc-paper-2"></i>
                                <p>Typography</p>
                            </a>
                        </li>
                        <li>
                            <a class="nav-link" href="./icons.html">
                                <i class="nc-icon nc-atom"></i>
                                <p>Icons</p>
                            </a>
                        </li>
                        <li>
                            <a class="nav-link" href="./maps.html">
                                <i class="nc-icon nc-pin-3"></i>
                                <p>Maps</p>
                            </a>
                        </li>
                        <li>
                            <a class="nav-link" href="./notifications.html">
                                <i class="nc-icon nc-bell-55"></i>
                                <p>Notifications</p>
                            </a>
                        </li>
                        <li class="nav-item active active-pro">
                          
                              @Html.ActionLink("Đăng xuất", "SignOut", "Admin")
                         
                        </li>
                        }
                       

                    </ul>
    
 
                </div>

            </div>

            <div class="main-panel">
                <!-- Navbar -->
                
                <!-- End Navbar -->
                <div class="content">
                    

                    @RenderBody()


                </div>
              
            </div>
        </div>
        <!--   -->
        <!-- <div class="fixed-plugin">
        <div class="dropdown show-dropdown">
            <a href="#" data-toggle="dropdown">
                <i class="fa fa-cog fa-2x"> </i>
            </a>

            <ul class="dropdown-menu">
                <li class="header-title"> Sidebar Style</li>
                <li class="adjustments-line">
                    <a href="javascript:void(0)" class="switch-trigger">
                        <p>Background Image</p>
                        <label class="switch">
                            <input type="checkbox" data-toggle="switch" checked="" data-on-color="primary" data-off-color="primary"><span class="toggle"></span>
                        </label>
                        <div class="clearfix"></div>
                    </a>
                </li>
                <li class="adjustments-line">
                    <a href="javascript:void(0)" class="switch-trigger background-color">
                        <p>Filters</p>
                        <div class="pull-right">
                            <span class="badge filter badge-black" data-color="black"></span>
                            <span class="badge filter badge-azure" data-color="azure"></span>
                            <span class="badge filter badge-green" data-color="green"></span>
                            <span class="badge filter badge-orange" data-color="orange"></span>
                            <span class="badge filter badge-red" data-color="red"></span>
                            <span class="badge filter badge-purple active" data-color="purple"></span>
                        </div>
                        <div class="clearfix"></div>
                    </a>
                </li>
                <li class="header-title">Sidebar Images</li>

                <li class="active">
                    <a class="img-holder switch-trigger" href="javascript:void(0)">
                        <img src="../assets/img/sidebar-1.jpg" alt="" />
                    </a>
                </li>
                <li>
                    <a class="img-holder switch-trigger" href="javascript:void(0)">
                        <img src="../assets/img/sidebar-3.jpg" alt="" />
                    </a>
                </li>
                <li>
                    <a class="img-holder switch-trigger" href="javascript:void(0)">
                        <img src="..//assets/img/sidebar-4.jpg" alt="" />
                    </a>
                </li>
                <li>
                    <a class="img-holder switch-trigger" href="javascript:void(0)">
                        <img src="../assets/img/sidebar-5.jpg" alt="" />
                    </a>
                </li>

                <li class="button-container">
                    <div class="">
                        <a href="http://www.creative-tim.com/product/light-bootstrap-dashboard" target="_blank" class="btn btn-info btn-block btn-fill">Download, it's free!</a>
                    </div>
                </li>

                <li class="header-title pro-title text-center">Want more components?</li>

                <li class="button-container">
                    <div class="">
                        <a href="http://www.creative-tim.com/product/light-bootstrap-dashboard-pro" target="_blank" class="btn btn-warning btn-block btn-fill">Get The PRO Version!</a>
                    </div>
                </li>

                <li class="header-title" id="sharrreTitle">Thank you for sharing!</li>

                <li class="button-container">
                    <button id="twitter" class="btn btn-social btn-outline btn-twitter btn-round sharrre"><i class="fa fa-twitter"></i> · 256</button>
                    <button id="facebook" class="btn btn-social btn-outline btn-facebook btn-round sharrre"><i class="fa fa-facebook-square"></i> · 426</button>
                </li>
            </ul>
        </div>
    </div>
     -->

    </div>
</body>
<script src="~/TemplateAdmin/assets/js/bootstrap-notify.js"></script>
<script src="~/TemplateAdmin/assets/js/bootstrap-select.js"></script>
<script src="~/TemplateAdmin/assets/js/bootstrap.min.js"></script>
<script src="~/TemplateAdmin/assets/js/chartist.min.js"></script>
<script src="~/TemplateAdmin/assets/js/demo.js"></script>
<script src="~/TemplateAdmin/assets/js/jquery.3.2.1.min.js"></script>
<script src="~/TemplateAdmin/assets/js/light-bootstrap-dashboard.js"></script>




<!--   Core JS Files   -->
<script src="../assets/js/core/jquery.3.2.1.min.js" type="text/javascript"></script>
<script src="../assets/js/core/popper.min.js" type="text/javascript"></script>
<script src="../assets/js/core/bootstrap.min.js" type="text/javascript"></script>
<!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
<script src="../assets/js/plugins/bootstrap-switch.js"></script>
<!--  Google Maps Plugin    -->
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
<!--  Chartist Plugin  -->
<script src="../assets/js/plugins/chartist.min.js"></script>
<!--  Notifications Plugin    -->
<script src="../assets/js/plugins/bootstrap-notify.js"></script>
<!-- Control Center for Light Bootstrap Dashboard: scripts for the example pages etc -->
<script src="../assets/js/light-bootstrap-dashboard.js?v=2.0.0 " type="text/javascript"></script>
<!-- Light Bootstrap Dashboard DEMO methods, don't include it in your project! -->
<script src="../assets/js/demo.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        // Javascript method's body can be found in assets/js/demos.js
        demo.initDashboardPageCharts();

        demo.showNotification();

    });
</script>
</html>

WebsiteBanSach/WebsiteBanSach/Views/Layout/NguoiDungLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @*file co san*@
    
    @*css cho dangnhapdangky*@
    <link href="~/Content/csswebbansach/css-nguoidunglayout.css" rel="stylesheet" />
    
    @*icon*@
    <link href="~/Content/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    
   
    @*chèn nivo slider quang cao*@

    <link href="~/NiviSlider/nivo-slider.css" rel="stylesheet">

    <script src="~/Scripts/jquery-1.8.2.min.js"></script>
    <script src="~/NiviSlider/jquery.nivo.slider.js"></script>
    <script src="~/NiviSlider/jquery.nivo.slider.pack.js"></script>

   
</head>
<body>
    
     
        <!-- Topbar Start -->
    <div class="toantrang">
        
        @*tao dang nhap dang ky*@
        <div class="DangKyDangNhap" style="font-size:15px;">
            <div class="div-dangkydangnhap">
                @Html.Action("GioHangPartial","GioHang")
                <i class="fa fa-registered" style="margin-left: 10px;" aria-hidden="true"></i>
                @Html.ActionLink("Admin", "Admin", "Admin", null, htmlAttributes: new { @class = "DangKy" })

                <i class="fa fa-sign-out" style="margin-left: 10px;" aria-hidden="true"></i>
            @Html.ActionLink("Đăng ký", "DangKy", "NguoiDung", null, htmlAttributes: new { @class = "DangKy" })

                <i class="fa fa-sign-out" style="margin-left: 10px;" aria-hidden="true"></i>
            @Html.ActionLink("Đăng nhập", "DangNhap", "NguoiDung", null, htmlAttributes: new { @class = "DangNhap" })
                <i class="fa fa-sign-out" style="margin-left: 10px;" aria-hidden="true"></i>
                @Html.ActionLink("Đăng xuất", "SignOut", "NguoiDung")
            </div>
        </div>

        <div class="heder">
            @*hop tim kiem*@
            <div class="txtTimKiem">
                @using (Html.BeginForm("KetQuaTimKiem","TimKiem",FormMethod.Post))
                {
                    @Html.TextBox("txtTimKiem", "", htmlAttributes: new { @class = "TextBoxTimKiem", @placeholder = "Nhập vào từ khóa cần tìm" })
                    <div class="nut">
                        <button style="border:none;" type="submit">
                           
                            <img src="~/hinhanh/search-icon-2.png" height="40px" width="40px"></img>
                        </button>
                    </div>
                    }
            </div>
            <div class="menu">
                <ul class="navMenu">
                    <li>
                        <a href="@Url.Action("Index","Home")">Trang chủ</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","GioiThieu")">Giới thiệu</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","LienHe")">Liên hệ</a>
                    </li>
                 
                    <li>
                        <a href="@Url.Action("Index","Home")">Sách</a>
                    </li>
                </ul>
            </div>
        </div>

        
        <section>
            @*div menu ben trai*@
            
                <div class="activity">
                    @*chen vao partial view*@
                    <div class="divbentrai">
                        @Html.Action("SachMoiPartial","Sach")
                   
                    </div>
              
            </div>
            <div id="slider" class="nivoSlider">
                @*chen anh nivo slider*@
                <img src="~/hinhanh/download (1).jfif" />
                <img src="~/hinhanh/download (2).jfif" />
                <img src="~/hinhanh/download (3).jfif" />
                <img src="~/hinhanh/download.jfif" />
            </div>
            <div style="clear:both;"></div>
        </section>
        @*div body*@
        <div id="NoiDung">

            @RenderBody()
        </div>
        <section>
            @* phan chu de*@
            <div style="margin-top: 50px;
    padding: 0 20px 0 20px;
    line-height: 100px;clear:left;">
               @Html.Action("ChuDePartial","ChuDe")
            </div>



        </section>

        
        @*div cho nha xuat ban*@
        <section class="blank-item">
            <div class="item">
                
                <div class="item-info">
                    @*action partialview*@
                    @Html.Action("NhaXuatBanPartial","NhaXuatBan")
                 
                </div>
             
            </div>
            <div class="divRight">
                @RenderSection("noidungbenphai",false)
            </div>



            <div style="clear:both"></div>
           
        </section>
        <div class="PhanCuoi">
            <a href="#" class="button button-buy">WEB BÁN SÁCH</a>
        </div>
      
      

       
      

    </div>
    @*script chay slider*@
    <script type="text/javascript">
        $(window).load(function () {
            $('#slider').nivoSlider({
                controlNav: false,
                nextText: '',
                prevText:''

            });
        });
    </script>


</body>
</html>