WebsiteBanSach/WebsiteBanSach/Controllers/QuanLySanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteBanSach.Models;
using PagedList;
using PagedList.Mvc;
using System.IO;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Data;
using System.Net;



namespace WebsiteBanSach.Controllers
{
    public class QuanLySanPhamController : Controller
    {
        //
        // GET: /QuanLySanPham/
        QuanLyBanSachEntities db = new QuanLyBanSachEntities();
    
        public ActionResult Index(int? page)
        {
            if (Session["TaiKhoan"] == null || Session["TaiKhoan"].ToString() == "")
            {
                return RedirectToAction("Admin", "Admin");
            }
            int pageNumber = (page ?? 1);
            int pageSize = 10;
            return View(db.Saches.ToList().OrderBy(n=>n.MaSach).ToPagedList(pageNumber,pageSize));
        }
        [HttpGet]
        public ActionResult ThemMoi()
        {
            //đưa du lieu vào dropdownlist
           ViewBag.MaNXB = new SelectList(db.NhaXuatBans.ToList().OrderBy(n => n.TenNXB), "MaNXB", "TenNXB");
            ViewBag.MaChuDe = new SelectList(db.ChuDes.ToList().OrderBy(n => n.TenChuDe), "MaChuDe", "TenChuDe");
            
            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
      

        public ActionResult ThemMoi(Sach sach , HttpPostedFileBase fileUpload )
        {
            if (Session["TaiKhoan"] == null || Session["TaiKhoan"].ToString() == "")
            {
                return RedirectToAction("Admin", "Admin");
            }
            
            // đưa dữ liệu vào
            ViewBag.MaNXB = new SelectList(db.NhaXuatBans.ToList().OrderBy(n => n.TenNXB), "MaNXB", "TenNXB");
            ViewBag.MaChuDe = new SelectList(db.ChuDes.ToList().OrderBy(n=>n.TenChuDe), "MaChuDe", "TenChuDe");
            //kiểm tra đường dẫn ảnh bìa 
            if(fileUpload == null)
            {
                ViewBag.ThongBao = "Chọn hình ảnh";
                return View();
            }
     //thêm cơ sơ dữ liêu
            if(ModelState.IsValid)
            {
                //lưu ten file
                var fileName = Path.GetFileName(fileUpload.FileName);
                //lưu đường dẫn file
                var path = Path.Combine(Server.MapPath("~/HinhAnhSP"), fileName);
                //kiểm tra hình ảnh đã tồn tại chưa
                if (System.IO.File.Exists(path))
                {
                    ViewBag.ThongBao = "Hình ảnh đã tồn tại";
                   
                }
                else
                {
                    fileUpload.SaveAs(path);
                }
                sach.AnhBia = fileUpload.FileName;

                db.Saches.Add(sach);
                db.SaveChanges();
            }

            return View();
        }




        //chỉnh sửa sản phẩm 
        [HttpGet]
       
        public ActionResult ChinhSua(int MaSach)
        {
            if (Session["TaiKhoan"] == null || Session["TaiKhoan"].ToString() == "")
            {
                return RedirectToAction("Admin", "Admin");
            }
            //lấy ra đối tượng theo ma
            Sach sach = db.Saches.SingleOrDefault(n => n.MaSach == MaSach);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }

            // đưa dữ liệu vào
            ViewBag.MaNXB = new SelectList(db.NhaXuatBans.ToList().OrderBy(n => n.TenNXB), "MaNXB", "TenNXB",sach.MaNXB);
            ViewBag.MaChuDe = new SelectList(db.ChuDes.ToList().OrderBy(n => n.TenChuDe), "MaChuDe", "TenChuDe",sach.MaChuDe);
            return View(sach);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ChinhSua(Sach sach,FormCollection f)
        {
            if (Session["TaiKhoan"] == null || Session["TaiKhoan"].ToString() == "")
            {
                return RedirectToAction("Admin", "Admin");
            }
           // Sach sach1 = db.Saches.SingleOrDefault(n => n.MaSach == sach.MaSach);
           // sach1.MoTa = sach.MoTa;
           // sach1.MoTa = f.Get("abc").ToString();
           // sach.MoTa = f["abc"].ToString();
            if (ModelState.IsValid)
            {

                //thực hiện cập nhật trong model
                db.Entry(sach).State = System.Data.EntityState.Modified;
                db.SaveChanges();
            }
            ViewBag.MaNXB = new SelectList(db.NhaXuatBans.ToList().OrderBy(n => n.TenNXB), "MaNXB", "TenNXB", sach.MaNXB);
            ViewBag.MaChuDe = new SelectList(db.ChuDes.ToList().OrderBy(n => n.TenChuDe), "MaChuDe", "TenChuDe", sach.MaChuDe);
            ViewBag.MaSach = sach.MaSach;
            
            return RedirectToAction("Index");
        }
        //hiện thị sản phẩm
        public ActionResult HienThi(int MaSach)
        {
            if (Session["TaiKhoan"] == null || Session["TaiKhoan"].ToString() == "")
            {
                return RedirectToAction("Admin", "Admin");
            }
            //lấy ra đối tượng theo ma
            Sach sach = db.Saches.SingleOrDefault(n => n.MaSach == MaSach);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }

           
            return View(sach);
        }
        //xóa sản phẩm
        [HttpGet]
        public ActionResult Xoa(int? MaSach)
        {
            if (Session["TaiKhoan"] == null || Session["TaiKhoan"].ToString() == "")
            {
                return RedirectToAction("Admin", "Admin");
            }
            //Sach sach = db.Saches.SingleOrDefault(n => n.MaSach == MaSach);
            //if (sach == null)
            //{
            //    Response.StatusCode = 404;
            //    return null;
            //}
            if(MaSach == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sach sach = db.Saches.Find(MaSach);
            if(sach == null)
            {
                return HttpNotFound();
            }
            return View(sach);
        }
        [HttpPost,ActionName("Xoa")]
        [ValidateAntiForgeryToken]
        public ActionResult XacNhanXoa(int MaSach)
        {
            if (Session["TaiKhoan"] == null || Session["TaiKhoan"].ToString() == "")
            {
                return RedirectToAction("Admin", "Admin");
            }
            //Sach sach = db.Saches.SingleOrDefault(n => n.MaSach == MaSach);
            //    if(sach==null)
            //    {
            //        Response.StatusCode=404;
            //        return null;
            //    }
            Sach sach = db.Saches.Find(MaSach);
            db.Saches.Remove(sach);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
     


    }
}

WebsiteBanSach/WebsiteBanSach/Views/QuanLySanPham/ChinhSua.cshtml
@model WebsiteBanSach.Models.Sach

@{
    ViewBag.Title = "ChinhSua";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}
<div class="ChinhSua">

<h2>Chỉnh sửa</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        

        <div class="editor-label">
            @Html.LabelFor(model => model.MaSach)

            <div class="editor-field">
                <span style="font-size:15px;margin-top:2px;margin-left:5px;">@Model.MaSach</span>
                @Html.Hidden("MaSach", Model.MaSach)
        </div>
    </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.TenSach)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TenSach)
            @Html.ValidationMessageFor(model => model.TenSach)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.GiaBan)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.GiaBan)
            @Html.ValidationMessageFor(model => model.GiaBan)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.MoTa)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MoTa)
            @Html.ValidationMessageFor(model => model.MoTa)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.AnhBia)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AnhBia)
            @Html.ValidationMessageFor(model => model.AnhBia)
        </div>
        @Html.TextBox("abc","abc")
        <div class="editor-label">
            @Html.LabelFor(model => model.NgayCapNhat)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.NgayCapNhat)
            @Html.ValidationMessageFor(model => model.NgayCapNhat)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.SoLuongTon)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SoLuongTon)
            @Html.ValidationMessageFor(model => model.SoLuongTon)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.MaNXB)
        </div>
        <div class="editor-field">
            @Html.DropDownList("MaNXB")
        
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.MaChuDe)
        </div>
        <div class="editor-field">
            @Html.DropDownList("MaChuDe")
           
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Moi)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Moi)
            @Html.ValidationMessageFor(model => model.Moi)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.MoTa)
        </div>
        <div class="editor-field">

            <textarea name="MoTa">@Model.MoTa</textarea>
        </div>
        <p>
            <input type="submit" value="Lưu" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
</div>

<style>
    fieldset {
        line-height:30px;
        
    }
    .ChinhSua{
        margin-left:10px;

    }
    div, input{
        margin-top:10px;
    }
</style>

WebsiteBanSach/WebsiteBanSach/Views/QuanLySanPham/HienThi.cshtml
@model WebsiteBanSach.Models.Sach

@{
    ViewBag.Title = "HienThi";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2>Hiển thị</h2>


   
<fieldset>
 

    <div class="display-label">
         @Html.DisplayNameFor(model => model.MaSach)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.MaSach)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.TenSach)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TenSach)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.GiaBan)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.GiaBan)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.MoTa)
    </div>
    <div class="display-field">
        @Html.Raw(Model.MoTa)
    </div>

    <div class="display-label">

         @Html.DisplayNameFor(model => model.AnhBia)
    
    <div class="display-field">
        @Html.DisplayFor(model => model.AnhBia)
      
      
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.NgayCapNhat)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NgayCapNhat)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.SoLuongTon)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SoLuongTon)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.NhaXuatBan.TenNXB)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NhaXuatBan.TenNXB)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ChuDe.TenChuDe)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ChuDe.TenChuDe)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Moi)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Moi)
    </div>
  
</fieldset>
<p>
    @Html.ActionLink("Chỉnh sửa", "ChinhSua", new { @MaSach=Model.MaSach }) |
    @Html.ActionLink("Trở về", "Index")
</p>

WebsiteBanSach/WebsiteBanSach/Views/QuanLySanPham/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model PagedList.PagedList<WebsiteBanSach.Models.Sach>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2>Quản lí sách</h2>

<p>
    @Html.ActionLink("Thêm mới sách", "ThemMoi")
</p>
<table class="bang-sach">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().MaSach)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().TenSach)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().GiaBan)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().MoTa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().AnhBia)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().NgayCapNhat)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().SoLuongTon)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().MaNXB)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().MaChuDe)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Moi)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.MaSach)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TenSach)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GiaBan)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MoTa)
        </td>
        <td>
            <div id="AnhBia"><img src="@Url.Content("~/HinhAnhSP/"+item.AnhBia)" width="100px" height="150px" /></div>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NgayCapNhat)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SoLuongTon)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NhaXuatBan.TenNXB)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MaChuDe)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Moi)
        </td>
        <td>
            <p>
            @Html.ActionLink("Chỉnh sửa", "ChinhSua", new { @MaSach=item.MaSach}) 
            </p>
            <p>
            @Html.ActionLink("Hiển thị", "HienThi", new { @MaSach = item.MaSach }) 
            </p>
            <p>
            @Html.ActionLink("Xóa", "Xoa", new { @MaSach = item.MaSach })
            </p>
        </td>
    </tr>
}

</table>
@*TẠO LINK LIEN KET TRANG*@
Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount
<div class="MenuTrang">

    @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
</div>

<style>
    td, th{
        border:2px solid;
        padding:10px;
        text-align:center;
     
    }
</style>

WebsiteBanSach/WebsiteBanSach/Views/QuanLySanPham/ThemMoi.cshtml
@model WebsiteBanSach.Models.Sach

@{
    ViewBag.Title = "ThemMoi";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2>ThemMoi</h2>

@using (Html.BeginForm("ThemMoi","QuanLySanPham" , FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Sach</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.MaSach)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MaSach)
            @Html.ValidationMessageFor(model => model.MaSach)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.TenSach)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TenSach)
            @Html.ValidationMessageFor(model => model.TenSach)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.GiaBan)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.GiaBan)
            @Html.ValidationMessageFor(model => model.GiaBan)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.MoTa)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MoTa)
            @Html.ValidationMessageFor(model => model.MoTa)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.AnhBia)
            <div class="editor-field">
                @Html.EditorFor(model => model.AnhBia)
                @Html.ValidationMessageFor(model => model.AnhBia)
                <input type="file" name="fileUpload" />
                @ViewBag.ThongBao
            </div>
        </div>
        
      
        <div class="editor-label">
            @Html.LabelFor(model => model.NgayCapNhat)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NgayCapNhat)
            @Html.ValidationMessageFor(model => model.NgayCapNhat)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.SoLuongTon)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SoLuongTon)
            @Html.ValidationMessageFor(model => model.SoLuongTon)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.MaNXB)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MaNXB)
            @Html.ValidationMessageFor(model => model.MaNXB)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.MaChuDe)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MaChuDe)
            @Html.ValidationMessageFor(model => model.MaChuDe)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Moi)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Moi)
            @Html.ValidationMessageFor(model => model.Moi)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebsiteBanSach/WebsiteBanSach/Views/QuanLySanPham/Xoa.cshtml
@model WebsiteBanSach.Models.Sach

@{
    ViewBag.Title = "Xoa";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}



<h3>Bạn có thật sự muốn xóa quyền sách này?</h3>
<fieldset>
    <legend>Sach</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.MaSach)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.MaSach)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.TenSach)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TenSach)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.GiaBan)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.GiaBan)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.MoTa)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.MoTa)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.AnhBia)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.AnhBia)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.NgayCapNhat)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NgayCapNhat)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.SoLuongTon)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SoLuongTon)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.NhaXuatBan.TenNXB)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NhaXuatBan.TenNXB)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ChuDe.TenChuDe)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ChuDe.TenChuDe)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Moi)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Moi)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Xóa" /> |
        @Html.ActionLink("Trở về", "Index")
    </p>
}